Регистрация:
<form action="/login/register" method="post">
    Login: <input type="text" name="name"> <br>
    Email: <input type="text" name="email"> <br>
    Password: <input type="password" name="password"> <br>
    Confirm Password: <input type="password" name="confirm_password"> <br>
    <input type="submit" value="Зарегистрироваться">
</form>
<br>
<br>

Войти
<form action="/login/auth" method="post">
    Email: <input type="text" name="email"> <br>
    Password: <input type="text" name="password"> <br>
    <input type="submit" value="Войти">
</form>

<br> 
<br>

